/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cianmcgovern_android_ShopAndShare_LoadingPage */

#ifndef _Included_com_cianmcgovern_android_ShopAndShare_LoadingPage
#define _Included_com_cianmcgovern_android_ShopAndShare_LoadingPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cianmcgovern_android_ShopAndShare_LoadingPage
 * Method:    callnativecode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cianmcgovern_android_ShopAndShare_LoadingPage_callnativecode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cianmcgovern_android_ShopAndShare_LoadingPage
 * Method:    getProducts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cianmcgovern_android_ShopAndShare_LoadingPage_getProducts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
