#ifdef ANDROID
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cianmcgovern_android_ShopAndStore_ShopAndStore */

#ifndef _Included_com_cianmcgovern_android_ShopAndStore_ShopAndStore
#define _Included_com_cianmcgovern_android_ShopAndStore_ShopAndStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cianmcgovern_android_ShopAndStore_ShopAndStore
 * Method:    callnativecode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cianmcgovern_android_ShopAndStore_ShopAndStore_callnativecode
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
#endif
